spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/bioskop_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver