spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://containers-us-west-130.railway.app:6413/railway

    # jdbc:postgresql://localhost:5432/bioskop_db
    username: postgres
    password: Z618Y3G2BNtPIFxLNeZT
    driver-class-name: org.postgresql.Driver
  server:
    port: 8082