spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://containers-us-west-117.railway.app:6553/railway

    # jdbc:postgresql://localhost:5432/bioskop_db
    username: postgres
    password: ansHcBEyN3Vkh9QPBT6c
    driver-class-name: org.postgresql.Driver
  server:
    port: 8082